service: songlist-tabs

provider:
  name: aws
  region: eu-west-1
  runtime: java11

package:
  artifact: target/songlist-tabs-latest.jar

plugins:
  - serverless-plugin-lambda-warmup

functions:
  songlist-tabs:
    handler: io.github.acm19.lambda.Handler
    environment:
      ARTIST_NAME: ${env:ARTIST_NAME}
    events:
      - http:
          path: tabRedirect
          method: get
